[package]
name = "evanalyzer_gui_slint"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }

# For Linux/macOS: slint's defaults plus Skia
[target.'cfg(not(target_os = "windows"))'.dependencies]
slint = { workspace = true, features = ["default", "renderer-skia"] }

# For Windows: Use Software Renderer (No Skia/VC++ requirement)
[target.'cfg(target_os = "windows")'.dependencies]
slint = { workspace = true, features = [
    "std",
    "compat-1-2",
    "renderer-software",
    "backend-winit",
] }

[build-dependencies]
slint-build = { workspace = true }
