[package]
name = "evanalyzer_gui"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }

[dependencies]
evanalyzer_core = { workspace = true }
evanalyzer_app = { path = "../app" }
evanalyzer_cfg = { path = "../cfg" }
evanalyzer_gui_slint = { path = "ui" }

rfd = "0.17"
copypasta = "0.10"
log = "0.4"
env_logger = "0.11"
rayon = "1.12"
kornia-image = { version = "0.1.14"}
kornia-imgproc = { version = "0.1.14"}
bitflags = "2.13.1"
enumset = "1.1.14"
clru = "0.6.3"
indexmap = "2.14.0"
bitvec = "1.1.1"
chrono = "0.4.45"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"



# For Linux/macOS: Use Skia
[target.'cfg(not(target_os = "windows"))'.dependencies.slint]
version = "1.17"
features = ["renderer-skia"]

# For Windows: Use Software Renderer (No Skia/VC++ requirement)
[target.'cfg(target_os = "windows")'.dependencies.slint]
version = "1.17"
default-features = false
features = [
    "std",
    "compat-1-2",
    "renderer-software",
    "backend-winit",
]

[dev-dependencies]
kornia-apriltag = {version = "0.1.10"}
i-slint-backend-testing = "=1.17.1"


