use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

use evanalyzer_cfg::core_types::{CitationMetadata, InternalErrors};
use evanalyzer_cfg::settings::project_settings::ProjectSettings;
use evanalyzer_core::into_algorithm;

/// Renders every enabled pipeline as an ASCII/Unicode flow diagram followed
/// by a consolidated reference list of every citation used, and writes the
/// result as a single markdown file to `output_file`.
/// Writes through `files` (the backend's), so the citation lands next to
/// the project wherever it lives.
pub fn cite_project(
    files: &dyn crate::api::FileSystem,
    config: &ProjectSettings,
    output_file: &PathBuf,
) -> Result<(), InternalErrors> {
    let mut out = String::new();
    let mut citations: BTreeMap<&'static str, &'static CitationMetadata> = BTreeMap::new();

    writeln!(out, "# Citations for \"{}\"", config.meta.name).ok();
    writeln!(out).ok();
    writeln!(out, "Generated by evanalyzer {}", env!("CARGO_PKG_VERSION")).ok();
    writeln!(out).ok();
    writeln!(out, "```text").ok();
    writeln!(out, "{}", "=".repeat(80)).ok();
    writeln!(out, "PIPELINE EXECUTION FLOW").ok();
    writeln!(out, "{}", "=".repeat(80)).ok();

    for pipeline_setting in &config.pipelines {
        if !pipeline_setting.enabled {
            continue;
        }

        let steps: Vec<_> = pipeline_setting
            .steps
            .iter()
            .filter(|step| step.enabled)
            .collect();

        writeln!(out).ok();
        writeln!(out, "Pipeline: {}", pipeline_setting.name).ok();

        let mut rows = Vec::with_capacity(steps.len());
        for (i, step) in steps.iter().enumerate() {
            let algo = into_algorithm(step.command.clone())?;
            let label = format!("[Step {}] {}", i + 1, algo.name());
            let cites = algo.cite();
            let citation_marker = if cites.is_empty() {
                "(Uncited)".to_string()
            } else {
                for cite in &cites {
                    citations.entry(cite.cite_key).or_insert(cite);
                }
                cites
                    .iter()
                    .map(|cite| format!("[@{}]", cite.cite_key))
                    .collect::<Vec<_>>()
                    .join(" ")
            };
            rows.push((label, citation_marker));
        }

        let target_col = rows
            .iter()
            .map(|(l, _)| l.chars().count())
            .max()
            .unwrap_or(0)
            + 4;

        for (i, (label, citation_marker)) in rows.iter().enumerate() {
            let is_last = i == rows.len() - 1;
            let connector = if is_last { "└──" } else { "├──" };
            let dots = target_col.saturating_sub(label.chars().count()).max(3);
            writeln!(
                out,
                " {} {} {} {}",
                connector,
                label,
                ".".repeat(dots),
                citation_marker
            )
            .ok();
        }
    }

    writeln!(out).ok();
    writeln!(out, "{}", "=".repeat(80)).ok();
    writeln!(out, "CITATIONS").ok();
    writeln!(out, "{}", "=".repeat(80)).ok();
    writeln!(out).ok();

    if citations.is_empty() {
        writeln!(out, "(No cited algorithms are used in this project)").ok();
    } else {
        for cite in citations.values() {
            writeln!(out, "[@{}]", cite.cite_key).ok();
            writeln!(
                out,
                "    {} ({}). {}.",
                cite.authors.join(", "),
                cite.year,
                cite.title
            )
            .ok();

            let mut trailer = Vec::new();
            if let Some(container) = cite.container {
                trailer.push(container.to_string());
            }
            if let Some(pages) = cite.pages {
                trailer.push(format!("pp. {}", pages));
            }
            if !trailer.is_empty() {
                writeln!(out, "    {}.", trailer.join(", ")).ok();
            }
            if let Some(doi) = cite.doi {
                writeln!(out, "    DOI: {}", doi).ok();
            } else if let Some(url) = cite.url {
                writeln!(out, "    {}", url).ok();
            }
            writeln!(out).ok();
        }
    }

    writeln!(out, "```").ok();

    files.write_file(output_file, out.as_bytes())?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use crate::backend::LocalFileSystem;

    use super::*;
    use evanalyzer_cfg::core_types::{ImageAddress, PipelineId};
    use evanalyzer_cfg::settings::pipeline_command::PipelineCommand;
    use evanalyzer_cfg::settings::pipeline_command_settings::{
        BlurSettings, GaussianBlurSettings, RollingBallSettings,
        SegmentationThresholdThresholdMethodSettings, ThresholdEntrySettings, ThresholdSettings,
    };
    use evanalyzer_cfg::settings::pipeline_settings::{PipelineSettings, PipelineStepSettings};

    #[test]
    fn a_step_with_several_citations_lists_all_of_them() {
        let entry = |method| ThresholdEntrySettings {
            method,
            ..Default::default()
        };
        let mut config = ProjectSettings::default();
        config.pipelines.push(PipelineSettings {
            id: PipelineId(1),
            name: "Two thresholds".to_string(),
            image_source: ImageAddress::Scratchpad,
            enabled: true,
            steps: vec![PipelineStepSettings {
                enabled: true,
                command: PipelineCommand::Threshold(ThresholdSettings {
                    thresholds: vec![
                        entry(SegmentationThresholdThresholdMethodSettings::Li),
                        entry(SegmentationThresholdThresholdMethodSettings::Triangle),
                    ],
                }),
            }],
            description: None,
        });

        let dir = tempfile::tempdir().unwrap();
        let output_file = dir.path().join("cite.md");
        cite_project(&LocalFileSystem::default(), &config, &output_file).unwrap();
        let content = std::fs::read_to_string(&output_file).unwrap();

        assert!(
            content.contains("[@li1993minimum] [@zack1977automatic]"),
            "{content}"
        );
        assert!(content.contains("Minimum cross entropy thresholding"));
        assert!(content.contains("Automatic measurement of sister chromatid exchange frequency"));
    }

    #[test]
    fn writes_ascii_flow_and_citations() {
        let mut config = ProjectSettings::default();
        config.meta.name = "Demo Project".to_string();
        config.pipelines.push(PipelineSettings {
            id: PipelineId(1),
            name: "Cell Segmentation & Background Subtraction".to_string(),
            image_source: ImageAddress::Scratchpad,
            enabled: true,
            steps: vec![
                PipelineStepSettings {
                    enabled: true,
                    command: PipelineCommand::RollingBall(RollingBallSettings::default()),
                },
                PipelineStepSettings {
                    enabled: true,
                    command: PipelineCommand::GaussianBlur(GaussianBlurSettings::default()),
                },
                PipelineStepSettings {
                    enabled: false,
                    command: PipelineCommand::Blur(BlurSettings { kernel_size: 3 }),
                },
            ],
            description: None,
        });

        let dir = tempfile::tempdir().unwrap();
        let output_file = dir.path().join("cite.md");
        cite_project(&LocalFileSystem::default(), &config, &output_file).unwrap();

        let content = std::fs::read_to_string(&output_file).unwrap();
        println!("{}", content);

        assert!(content.contains("Demo Project"));
        assert!(content.contains("├── [Step 1] Rolling Ball"));
        assert!(content.contains("└── [Step 2] Gaussian Blur"));
        // Gaussian Blur has no published method of its own: it cites EVAnalyzer.
        assert!(!content.contains("(Uncited)"));
        assert!(content.contains("[@danmayr2026]"));
        assert!(content.contains("EVAnalyzer: Enhanced Visual Analyzer"));
        assert!(!content.contains("[Step 3]"));
        assert!(content.contains("[@sternberg1983biomedical]"));
        assert!(content.contains("Sternberg"));
    }
}
