[package]
name = "evanalyzer_cli"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
evanalyzer_core = { workspace = true }
evanalyzer_app = { path = "../app" }
evanalyzer_cfg = { path = "../cfg" }
clap = { version = "4", features = ["derive"] }
