import { BaseDialog } from "dialog_base.slint";
import { Button } from "std-widgets.slint";
import {
    Palette,
} from "std-widgets.slint";
import {
    GlobalAppState,
    DialogType,
} from "../state.slint";

import { ObjectListState } from "../editor/object_list_panel.slint";
import { AppButton } from "../components/app_button.slint";

export component ConfirmDeleteManualAnnotatedObjectDialog inherits BaseDialog {
    title-text: "Delete objects";
    icon: "⚠️";
    main-height: 260px;
    main-width: 440px;

    VerticalLayout {
        spacing: 12px;
        Text {
            text: "This action cannot be undone. Deleting all manual annotated objects.";
            wrap: word-wrap;
            color: Palette.foreground;
            font-size: 14px;
            font-weight: 500;
        }

        Text {
            text: "Delete all manual annotated objects.";
            wrap: word-wrap;
            color: Palette.foreground.with-alpha(0.5);
            font-size: 13px;
        }

        Rectangle {
            vertical-stretch: 1;
        }

        HorizontalLayout {
            spacing: 12px;
            alignment: end;

            AppButton {
                text: "Cancel";
                width: 80px;
                clicked => {
                    GlobalAppState.active_dialog = DialogType.none;
                }
            }

            AppButton {
                text: "Delete";
                width: 100px;
                danger: true;
                clicked => {
                    GlobalAppState.active_dialog = DialogType.none;
                    ObjectListState.object_delete_all_manual_annotated();
                    ObjectListState.selected_object = { };
                }
            }
        }
    }
}
