import { BaseDialog } from "dialog_base.slint";
import { GlobalAppState, DialogType, UnsavedChangesState } from "../state.slint";
import { AppButton } from "../components/app_button.slint";
import { Theme } from "../style.slint";

export component UnsavedChangesDialog inherits BaseDialog {
    title-text: "Unsaved changes";
    icon: "⚠️";
    main-height: 220px;
    main-width: 440px;

    VerticalLayout {
        spacing: 12px;
        Text {
            text: "This project has unsaved changes. Do you want to save them before continuing?";
            wrap: word-wrap;
            color: Theme.text;
            font-size: 14px;
            font-weight: 500;
        }

        Rectangle {
            vertical-stretch: 1;
        }

        HorizontalLayout {
            spacing: 12px;
            alignment: end;

            AppButton {
                text: "Cancel";
                clicked => {
                    GlobalAppState.active-dialog = DialogType.none;
                    UnsavedChangesState.cancel();
                }
            }

            AppButton {
                text: "Discard changes";
                danger: true;
                clicked => {
                    GlobalAppState.active-dialog = DialogType.none;
                    UnsavedChangesState.discard();
                }
            }

            AppButton {
                text: "Save";
                clicked => {
                    GlobalAppState.active-dialog = DialogType.none;
                    UnsavedChangesState.save();
                }
            }
        }
    }
}
