[package]
name = "evanalyzer_app"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }

[dependencies]
evanalyzer_core = { workspace = true }
evanalyzer_cfg = { workspace = true }

log = { workspace = true }
chrono = { workspace = true }
indexmap = { workspace = true }
bitvec = { workspace = true }
pathdiff = { workspace = true }
rayon = { workspace = true }
human-sort ={ workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
regex = { workspace = true }
csv = { workspace = true }
rust_xlsxwriter = { workspace = true , features = ["constant_memory"] }
dirs = { workspace = true }
image = { workspace = true }
duckdb = { workspace = true }


[dev-dependencies]
tempfile = { workspace = true }
duckdb = { workspace = true, features = ["bundled"] }
calamine = "0.36.1"

[lib]
name = "evanalyzer_app"
path = "src/lib.rs"
doctest = false
