[package]
name = "evanalyzer_app"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }

[dependencies]
evanalyzer_core = { workspace = true }
evanalyzer_cfg = { workspace = true }

log = { workspace = true }
chrono = { workspace = true }
indexmap = { workspace = true }
bitvec = { workspace = true }
pathdiff = "0.2.3"
rayon = { workspace = true }
human-sort = "0.2"
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
regex = "1"
csv = { workspace = true }
rust_xlsxwriter = { version = "0.97.1", features = ["constant_memory"] }
dirs = "6"
plotters = { version = "0.3", default-features = false, features = ["bitmap_backend", "bitmap_encoder", "point_series", "ttf"] }
image = { workspace = true }


[dev-dependencies]
tempfile = { workspace = true }
duckdb = { workspace = true, features = ["bundled"] }
calamine = "0.36.1"

[lib]
name = "evanalyzer_app"
path = "src/lib.rs"
doctest = false
