[package]
name = "evanalyzer_app"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }

[dependencies]
evanalyzer_core = { workspace = true }
evanalyzer_cfg = { path = "../cfg" }

log = "0.4"
env_logger = "0.11"
indexmap = "2.14.0"
bitvec = "1.1.1"
pathdiff = "0.2.3"
rayon = "1.12.0"
human-sort = "0.2"
serde = "1.0.229"
serde_json = "1.0.151"
serde_yaml = "0.9"
regex = "1"
csv = "1"
rust_xlsxwriter = { version = "0.97.1", features = ["constant_memory"] }
dirs = "6"
plotters = { version = "0.3", default-features = false, features = ["bitmap_backend", "bitmap_encoder", "point_series", "ttf"] }
image = "0.25.10"


[dev-dependencies]
tempfile = "3"
duckdb = { version = "1.1.3", features = ["bundled"] }
calamine = "0.36.1"

[lib]
name = "evanalyzer_app"
path = "src/lib.rs"
doctest = false
