[package]
name = "evanalyzer_server"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }


[dependencies]
log = { workspace = true }
env_logger = { workspace = true }
tungstenite = { workspace = true }
yescrypt = { version = "0.1.0", default-features = false, features = ["password-hash"] }
sha-crypt = "0.6.0"
serde_json = { workspace = true }
getrandom = { workspace = true }
serde = { workspace = true, features = ["derive","rc"] }

[dev-dependencies]
tempfile = { workspace = true }
